### ISSUE TITLE
Wrong output `detectQueryType`

### ISSUE THREAD

**Issue by TJhon** [d2cml-ai/wb-project-analysis#2]
With `detectQueryType` (router branch), you can correctly detect whether any project id is received. However, when you input a `Report No: ...`, it returns a list, which is incorrect, and none of the items on the list match the correct `repnb`.

Original Pdf: https://documents1.worldbank.org/curated/en/127181606851449191/pdf/Haiti-Digital-Acceleration-Project.pdf
Query: `Report No: PAD3745`

![image](https://github.com/d2cml-ai/wb-project-analysis/assets/48776907/b19737f2-e40d-4a58-b3c8-b2f1ce62dd30)

**Comment by RodrigoGrijalba** [comment]
The changes to the router and the processing of report numbers are in the `app` branch and not yet merged into `main`.

I attempted the same query in the `app` branch and got the following result:

![reportNo_query_result](https://github.com/d2cml-ai/wb-project-analysis/assets/80277672/1b3f5506-2b12-4030-b3cd-6550233b372c)

Which is correct

**Comment by RodrigoGrijalba** [comment]
#4 now implements this to the main app
